telemetry = false

[test]
concurrentTestGlob = "**/*.test.ts"
timeout = 5000
coverageSkipTestFiles = true
pathIgnorePatterns = [
  "**/dist/**",
  "**/node_modules/**",
  "**/tmp/**",
  "**/fixtures/**",
  "**/test/**",
  "**/coverage/**",
  "**/references/**",
]

[install]
minimumReleaseAge = 259200 # 3 days in seconds
minimumReleaseAgeExcludes = ["@types/bun", "typescript", "oxfmt", "oxlint", "oxlint-tsgolint"]
